### ISSUE TITLE
Mismatching ABI between ArduinoRuntime and the rest of the targets

### ISSUE THREAD

**Issue by AeroStun** [DIT112-V20/group-09#71]
Direct cause of [this CI failure](https://github.com/DIT112-V20/group-09/pull/69/checks?check_run_id=682619954)

**Comment by AeroStun** [comment]
Update: within a single stacktrace, two frames accessing the same address obtain different results
![image](https://user-images.githubusercontent.com/24841307/82148309-b7b4ac00-9853-11ea-91d3-ae3723910ea6.png)
![image](https://user-images.githubusercontent.com/24841307/82148350-e6328700-9853-11ea-87f1-fc9852982eeb.png)

**Comment by AeroStun** [comment]
Only possible explanation is that the DLL somehow ends up with a different virtual memory space, but this is supposedly impossible since previous demos have demonstrated that user-code actions can be observed by the main thread

**Comment by AeroStun** [comment]
Better yet, with Clang: from a single stack frame, depending on how the pointer to the object is accessed, different results are obtained (see that from the lambda I get a `pin_modes` of size 1, and from the global, which point at the same address, I get a `pin_modes` of size 0)
![image](https://user-images.githubusercontent.com/24841307/82157581-9a4b0680-9882-11ea-907f-f7f1630eaa33.png)

**Comment by AeroStun** [comment]
Update: tried setting an x86 hardware watchpoint using LLDB on `board_info->pins_caps._M_impl._M_start` (yes I use libstdc++), and the watchpoint does not fire

**Comment by AeroStun** [comment]
We have reached a whole other level
![image](https://user-images.githubusercontent.com/24841307/82161184-df7b3280-989a-11ea-93a6-8aa8b628e151.png)

**Comment by AeroStun** [comment]
It only gets better...
![Screenshot_20200518_002130](https://user-images.githubusercontent.com/24841307/82161589-5d8d0880-989e-11ea-9daf-2fec212700db.jpg)

**Comment by AeroStun** [comment]
Have I mentionned that debuggers are useless?
![image](https://user-images.githubusercontent.com/24841307/82203621-d83c3f00-9903-11ea-9cb0-c16d27678636.png)

**Comment by platisd** [comment]
This seems like the definition of an undefined behavior. Is there something that's not initialized perhaps?

**Comment by AeroStun** [comment]
Undefined behavior does not affect operator `sizeof` since its operands are unevaluated (only the type of the expression is used)
I suspect that LLDB is trying to JIT some of its evaluations with different build options

**Comment by AeroStun** [comment]
Next assumption: broken ABI

**Comment by AeroStun** [comment]
CONFIRMED: broken ABI
- SMCE and its tests compile in non-debug mode, hence they use `std::__cxx1998::vector`
- ArduinoRuntime compiles in debug mode, hence it uses the 56 bytes long (why the hell do they use that extra space for? Gotta go read their debug impl now) `std::__debug::vector`

**Comment by AeroStun** [comment]
Morale of the story: too much debugging kills the debugging
And second morale is that debuggers can't be trusted since they don't tell the user how they got the results from expression evaluation; only Valgrind stands trustworthy
